LINKS:
  ESPN_TEAMS: "https://site.api.espn.com/apis/site/v2/sports/baseball/mlb/teams?limit=200000"
  TEAM_DETAILS:
    - "https://en.wikipedia.org/wiki/Arizona_Diamondbacks"
    - "https://en.wikipedia.org/wiki/Athletics_(baseball)"
    - "https://en.wikipedia.org/wiki/Atlanta_Braves"
    - "https://en.wikipedia.org/wiki/Baltimore_Orioles"
    - "https://en.wikipedia.org/wiki/Boston_Red_Sox"
    - "https://en.wikipedia.org/wiki/Chicago_Cubs"
    - "https://en.wikipedia.org/wiki/Chicago_White_Sox"
    - "https://en.wikipedia.org/wiki/Cincinnati_Reds"
    - "https://en.wikipedia.org/wiki/Cleveland_Guardians"
    - "https://en.wikipedia.org/wiki/Colorado_Rockies"
    - "https://en.wikipedia.org/wiki/Detroit_Tigers"
    - "https://en.wikipedia.org/wiki/Houston_Astros"
    - "https://en.wikipedia.org/wiki/Kansas_City_Royals"
    - "https://en.wikipedia.org/wiki/Los_Angeles_Angels"
    - "https://en.wikipedia.org/wiki/Los_Angeles_Dodgers"
    - "https://en.wikipedia.org/wiki/Miami_Marlins"
    - "https://en.wikipedia.org/wiki/Milwaukee_Brewers"
    - "https://en.wikipedia.org/wiki/Minnesota_Twins"
    - "https://en.wikipedia.org/wiki/New_York_Mets"
    - "https://en.wikipedia.org/wiki/New_York_Yankees"
    - "https://en.wikipedia.org/wiki/Philadelphia_Phillies"
    - "https://en.wikipedia.org/wiki/Pittsburgh_Pirates"
    - "https://en.wikipedia.org/wiki/San_Diego_Padres"
    - "https://en.wikipedia.org/wiki/San_Francisco_Giants"
    - "https://en.wikipedia.org/wiki/Seattle_Mariners"
    - "https://en.wikipedia.org/wiki/St_Louis_Cardinals"
    - "https://en.wikipedia.org/wiki/Tampa_Bay_Rays"
    - "https://en.wikipedia.org/wiki/Texas_Rangers_(baseball)"
    - "https://en.wikipedia.org/wiki/Toronto_Blue_Jays"
    - "https://en.wikipedia.org/wiki/Washington_Nationals"
ATTRIBUTES:
  TEAM_DETAILS:
    NAME: "//th[contains(@class, 'infobox-above') and contains(@class, 'fn')]/text()"
    ARENA: "//tr[th[contains(., 'Ballpark')]]/following-sibling::tr[1]/td//a | //tr[th[contains(., 'Ballpark')]]/td//a"
    COACH: "//th[@class='infobox-label'][contains(., 'Manager')]/following-sibling::td[1]"
    MANAGER: "//th[@class='infobox-label'][contains(., 'General manager')]/following-sibling::td[1]"
    CONFERENCE: "(//*[@id='mw-content-text']/div[1]/table[1]/tbody/tr[6]/td/div/ul/li/a[1] | //*[@id='mw-content-text']/div[1]/table[2]/tbody/tr[6]/td/div/ul/li/a[1])"
    DIVISION: "//div[contains(@style, 'text-align:left;')]//ul/li/ul/li/a[contains(text(), 'Division')]/text()"
