LINKS:
  ESPN_TEAMS: "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/teams?limit=200000"
  GENERAL_MANAGERS : "https://en.wikipedia.org/wiki/List_of_NBA_general_managers"
  TEAM_DETAILS:
    - "https://en.wikipedia.org/wiki/Atlanta_Hawks"
    - "https://en.wikipedia.org/wiki/Boston_Celtics"
    - "https://en.wikipedia.org/wiki/Brooklyn_Nets"
    - "https://en.wikipedia.org/wiki/Charlotte_Hornets"
    - "https://en.wikipedia.org/wiki/Chicago_Bulls"
    - "https://en.wikipedia.org/wiki/Cleveland_Cavaliers"
    - "https://en.wikipedia.org/wiki/Dallas_Mavericks"
    - "https://en.wikipedia.org/wiki/Denver_Nuggets"
    - "https://en.wikipedia.org/wiki/Detroit_Pistons"
    - "https://en.wikipedia.org/wiki/Golden_State_Warriors"
    - "https://en.wikipedia.org/wiki/Houston_Rockets"
    - "https://en.wikipedia.org/wiki/Indiana_Pacers"
    - "https://en.wikipedia.org/wiki/LA_Clippers"
    - "https://en.wikipedia.org/wiki/Los_Angeles_Lakers"
    - "https://en.wikipedia.org/wiki/Memphis_Grizzlies"
    - "https://en.wikipedia.org/wiki/Miami_Heat"
    - "https://en.wikipedia.org/wiki/Milwaukee_Bucks"
    - "https://en.wikipedia.org/wiki/Minnesota_Timberwolves"
    - "https://en.wikipedia.org/wiki/New_Orleans_Pelicans"
    - "https://en.wikipedia.org/wiki/New_York_Knicks"
    - "https://en.wikipedia.org/wiki/Oklahoma_City_Thunder"
    - "https://en.wikipedia.org/wiki/Orlando_Magic"
    - "https://en.wikipedia.org/wiki/Philadelphia_76ers"
    - "https://en.wikipedia.org/wiki/Phoenix_Suns"
    - "https://en.wikipedia.org/wiki/Portland_Trail_Blazers"
    - "https://en.wikipedia.org/wiki/Sacramento_Kings"
    - "https://en.wikipedia.org/wiki/San_Antonio_Spurs"
    - "https://en.wikipedia.org/wiki/Toronto_Raptors"
    - "https://en.wikipedia.org/wiki/Utah_Jazz"
    - "https://en.wikipedia.org/wiki/Washington_Wizards"
ATTRIBUTES:
  TEAM_DETAILS:
    NAME: "//th[@class='infobox-above fn org']/text()"
    ARENA: "//th[@class='infobox-label'][contains(., 'Arena')]/following-sibling::td[1]"
    COACH: "//th[@class='infobox-label'][contains(., 'Head coach')]/following-sibling::td[1]"
    CONFERENCE: "//th[@class='infobox-label'][contains(., 'Conference')]/following-sibling::td[1]"
    DIVISION: "//th[@class='infobox-label'][contains(., 'Division')]/following-sibling::td[1]"
