LINKS:
  ESPN_TEAMS: "https://site.api.espn.com/apis/site/v2/sports/basketball/wnba/teams?limit=200000"
  PLAYERS_ESPN: "https://sports.core.api.espn.com/v3/sports/basketball/wnba/athletes?limit=20000&active=true"
  ESPN_DETAILED: "https://site.api.espn.com/apis/common/v3/sports/basketball/wnba/athletes/{id}"
  TEAM_DETAILS:
    - "https://en.wikipedia.org/wiki/Atlanta_Dream"
    - "https://en.wikipedia.org/wiki/Chicago_Sky"
    - "https://en.wikipedia.org/wiki/Connecticut_Sun"
    - "https://en.wikipedia.org/wiki/Indiana_Fever"
    - "https://en.wikipedia.org/wiki/New_York_Liberty"
    - "https://en.wikipedia.org/wiki/Washington_Mystics"
    - "https://en.wikipedia.org/wiki/Dallas_Wings"
    - "https://en.wikipedia.org/wiki/Golden_State_Valkyries"
    - "https://en.wikipedia.org/wiki/Las_Vegas_Aces"
    - "https://en.wikipedia.org/wiki/Los_Angeles_Sparks"
    - "https://en.wikipedia.org/wiki/Minnesota_Lynx"
    - "https://en.wikipedia.org/wiki/Phoenix_Mercury"
    - "https://en.wikipedia.org/wiki/Seattle_Storm"
  VENUES:
    - "https://en.wikipedia.org/wiki/Gateway_Center_Arena"
    - "https://en.wikipedia.org/wiki/Wintrust_Arena"
    - "https://en.wikipedia.org/wiki/Mohegan_Sun_Arena"
    - "https://en.wikipedia.org/wiki/Gainbridge_Fieldhouse"
    - "https://en.wikipedia.org/wiki/Barclays_Center"
    - "https://en.wikipedia.org/wiki/CareFirst_Arena"
    - "https://en.wikipedia.org/wiki/College_Park_Center"
    - "https://en.wikipedia.org/wiki/Chase_Center"
    - "https://en.wikipedia.org/wiki/Michelob_Ultra_Arena"
    - "https://en.wikipedia.org/wiki/Crypto.com_Arena"
    - "https://en.wikipedia.org/wiki/Target_Center"
    - "https://en.wikipedia.org/wiki/PHX_Arena"
    - "https://en.wikipedia.org/wiki/Climate_Pledge_Arena"
ATTRIBUTES:
  TEAM_DETAILS:
    NAME: "//th[@class='infobox-above fn org']/text()"
    ARENA: "//th[@class='infobox-label'][contains(., 'Arena')]/following-sibling::td[1]"
    COACH: "//th[@class='infobox-label'][contains(., 'Head coach')]/following-sibling::td[1]"
    CONFERENCE: "//th[@class='infobox-label'][contains(., 'Conference')]/following-sibling::td[1]"
    GENERAL_MANAGER: "//th[@class='infobox-label'][contains(., 'General manager')]/following-sibling::td[1]"
  VENUES:
    NAME: "//table[contains(@class,'infobox')]//caption"
    LOCATION: "//tr[th[normalize-space(.)='Location']]/td/a[1]"
    CAPACITY: "//th[@class='infobox-label'][contains(., 'Capacity')]/following-sibling::td[1]"
    SURFACE: "//th[@class='infobox-label'][contains(., 'Surface')]/following-sibling::td[1]"
    LATLON_DECIMAL: "//span[contains(@class, 'geo-dec')]/text()"
    WEBSITE: "//tr[th[contains(., 'Website')]]/following-sibling::tr[1]/td//a/@href"
