LINKS:
  ESPN_TEAMS: "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/teams?limit=200000"
  GENERAL_MANAGERS : "https://en.wikipedia.org/wiki/List_of_NBA_general_managers"
  OPENED: "https://en.wikipedia.org/wiki/List_of_NBA_arenas"
  PLAYERS_ESPN: "https://sports.core.api.espn.com/v3/sports/basketball/nba/athletes?limit=20000&active=true"
  ESPN_DETAILED: "https://site.api.espn.com/apis/common/v3/sports/basketball/nba/athletes/{id}"
  TEAM_DETAILS:
    - "https://en.wikipedia.org/wiki/Atlanta_Hawks"
    - "https://en.wikipedia.org/wiki/Boston_Celtics"
    - "https://en.wikipedia.org/wiki/Brooklyn_Nets"
    - "https://en.wikipedia.org/wiki/Charlotte_Hornets"
    - "https://en.wikipedia.org/wiki/Chicago_Bulls"
    - "https://en.wikipedia.org/wiki/Cleveland_Cavaliers"
    - "https://en.wikipedia.org/wiki/Dallas_Mavericks"
    - "https://en.wikipedia.org/wiki/Denver_Nuggets"
    - "https://en.wikipedia.org/wiki/Detroit_Pistons"
    - "https://en.wikipedia.org/wiki/Golden_State_Warriors"
    - "https://en.wikipedia.org/wiki/Houston_Rockets"
    - "https://en.wikipedia.org/wiki/Indiana_Pacers"
    - "https://en.wikipedia.org/wiki/LA_Clippers"
    - "https://en.wikipedia.org/wiki/Los_Angeles_Lakers"
    - "https://en.wikipedia.org/wiki/Memphis_Grizzlies"
    - "https://en.wikipedia.org/wiki/Miami_Heat"
    - "https://en.wikipedia.org/wiki/Milwaukee_Bucks"
    - "https://en.wikipedia.org/wiki/Minnesota_Timberwolves"
    - "https://en.wikipedia.org/wiki/New_Orleans_Pelicans"
    - "https://en.wikipedia.org/wiki/New_York_Knicks"
    - "https://en.wikipedia.org/wiki/Oklahoma_City_Thunder"
    - "https://en.wikipedia.org/wiki/Orlando_Magic"
    - "https://en.wikipedia.org/wiki/Philadelphia_76ers"
    - "https://en.wikipedia.org/wiki/Phoenix_Suns"
    - "https://en.wikipedia.org/wiki/Portland_Trail_Blazers"
    - "https://en.wikipedia.org/wiki/Sacramento_Kings"
    - "https://en.wikipedia.org/wiki/San_Antonio_Spurs"
    - "https://en.wikipedia.org/wiki/Toronto_Raptors"
    - "https://en.wikipedia.org/wiki/Utah_Jazz"
    - "https://en.wikipedia.org/wiki/Washington_Wizards"
  VENUES:
    - "https://en.wikipedia.org/wiki/American_Airlines_Center"
    - "https://en.wikipedia.org/wiki/Ball_Arena"
    - "https://en.wikipedia.org/wiki/Barclays_Center"
    - "https://en.wikipedia.org/wiki/Capital_One_Arena"
    - "https://en.wikipedia.org/wiki/Chase_Center"
    - "https://en.wikipedia.org/wiki/Crypto.com_Arena"
    - "https://en.wikipedia.org/wiki/Delta_Center"
    - "https://en.wikipedia.org/wiki/FedExForum"
    - "https://en.wikipedia.org/wiki/Fiserv_Forum"
    - "https://en.wikipedia.org/wiki/Frost_Bank_Center"
    - "https://en.wikipedia.org/wiki/Gainbridge_Fieldhouse"
    - "https://en.wikipedia.org/wiki/Golden_1_Center"
    - "https://en.wikipedia.org/wiki/Intuit_Dome"
    - "https://en.wikipedia.org/wiki/Kaseya_Center"
    - "https://en.wikipedia.org/wiki/Kia_Center"
    - "https://en.wikipedia.org/wiki/Little_Caesars_Arena"
    - "https://en.wikipedia.org/wiki/Madison_Square_Garden"
    - "https://en.wikipedia.org/wiki/Moda_Center"
    - "https://en.wikipedia.org/wiki/Paycom_Center"
    - "https://en.wikipedia.org/wiki/PHX_Arena"
    - "https://en.wikipedia.org/wiki/Rocket_Mortgage_FieldHouse"
    - "https://en.wikipedia.org/wiki/Scotiabank_Arena"
    - "https://en.wikipedia.org/wiki/Smoothie_King_Center"
    - "https://en.wikipedia.org/wiki/Spectrum_Center"
    - "https://en.wikipedia.org/wiki/State_Farm_Arena"
    - "https://en.wikipedia.org/wiki/Target_Center"
    - "https://en.wikipedia.org/wiki/TD_Garden"
    - "https://en.wikipedia.org/wiki/Toyota_Center"
    - "https://en.wikipedia.org/wiki/United_Center"
    - "https://en.wikipedia.org/wiki/Wells_Fargo_Center_(Philadelphia)"
ATTRIBUTES:
  TEAM_DETAILS:
    NAME: "//th[@class='infobox-above fn org']/text()"
    ARENA: "//th[@class='infobox-label'][contains(., 'Arena')]/following-sibling::td[1]"
    COACH: "//th[@class='infobox-label'][contains(., 'Head coach')]/following-sibling::td[1]"
    CONFERENCE: "//th[@class='infobox-label'][contains(., 'Conference')]/following-sibling::td[1]"
    DIVISION: "//th[@class='infobox-label'][contains(., 'Division')]/following-sibling::td[1]"
  VENUES:
    NAME: "//table[contains(@class,'infobox')]//caption"
    LOCATION: "//tr[th[normalize-space(.)='Location']]/td/a[1]"
    CAPACITY: "//th[@class='infobox-label'][contains(., 'Capacity')]/following-sibling::td[1]"
    SURFACE: "//th[@class='infobox-label'][contains(., 'Surface')]/following-sibling::td[1]"
    LATLON_DECIMAL: "//span[contains(@class, 'geo-dec')]/text()"
    WEBSITE: "//tr[th[contains(., 'Website')]]/following-sibling::tr[1]/td//a/@href"
