LINKS:
  ESPN_TEAMS: "https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams?limit=200000"
  OFFENSIVE_COORDINATORS: "https://en.wikipedia.org/wiki/List_of_current_NFL_offensive_coordinators"
  DEFENSIVE_COORDINATORS: "https://en.wikipedia.org/wiki/List_of_current_NFL_defensive_coordinators"
  VENUE_ROOF: "https://en.wikipedia.org/wiki/List_of_current_NFL_stadiums"
  PLAYERS_ESPN: "https://sports.core.api.espn.com/v3/sports/football/nfl/athletes?limit=20000&active=true"
  ESPN_DETAILED: "https://site.api.espn.com/apis/common/v3/sports/football/nfl/athletes/{id}"
  TEAM_DETAILS:
    - "https://www.nfl.com/teams/arizona-cardinals/"
    - "https://www.nfl.com/teams/atlanta-falcons/"
    - "https://www.nfl.com/teams/baltimore-ravens/"
    - "https://www.nfl.com/teams/buffalo-bills/"
    - "https://www.nfl.com/teams/carolina-panthers/"
    - "https://www.nfl.com/teams/chicago-bears/"
    - "https://www.nfl.com/teams/cincinnati-bengals/"
    - "https://www.nfl.com/teams/cleveland-browns/"
    - "https://www.nfl.com/teams/dallas-cowboys/"
    - "https://www.nfl.com/teams/denver-broncos/"
    - "https://www.nfl.com/teams/detroit-lions/"
    - "https://www.nfl.com/teams/green-bay-packers/"
    - "https://www.nfl.com/teams/houston-texans/"
    - "https://www.nfl.com/teams/indianapolis-colts/"
    - "https://www.nfl.com/teams/jacksonville-jaguars/"
    - "https://www.nfl.com/teams/kansas-city-chiefs/"
    - "https://www.nfl.com/teams/las-vegas-raiders/"
    - "https://www.nfl.com/teams/los-angeles-chargers/"
    - "https://www.nfl.com/teams/los-angeles-rams/"
    - "https://www.nfl.com/teams/miami-dolphins/"
    - "https://www.nfl.com/teams/minnesota-vikings/"
    - "https://www.nfl.com/teams/new-england-patriots/"
    - "https://www.nfl.com/teams/new-orleans-saints/"
    - "https://www.nfl.com/teams/new-york-giants/"
    - "https://www.nfl.com/teams/new-york-jets/"
    - "https://www.nfl.com/teams/philadelphia-eagles/"
    - "https://www.nfl.com/teams/pittsburgh-steelers/"
    - "https://www.nfl.com/teams/san-francisco-49ers/"
    - "https://www.nfl.com/teams/seattle-seahawks/"
    - "https://www.nfl.com/teams/tampa-bay-buccaneers/"
    - "https://www.nfl.com/teams/tennessee-titans/"
    - "https://www.nfl.com/teams/washington-commanders/"
  VENUES:
    - "https://en.wikipedia.org/wiki/Acrisure_Stadium"
    - "https://en.wikipedia.org/wiki/Allegiant_Stadium"
    - "https://en.wikipedia.org/wiki/Arrowhead_Stadium"
    - "https://en.wikipedia.org/wiki/AT%26T_Stadium"
    - "https://en.wikipedia.org/wiki/Bank_of_America_Stadium"
    - "https://en.wikipedia.org/wiki/Caesars_Superdome"
    - "https://en.wikipedia.org/wiki/Empower_Field_at_Mile_High"
    - "https://en.wikipedia.org/wiki/EverBank_Stadium"
    - "https://en.wikipedia.org/wiki/Ford_Field"
    - "https://en.wikipedia.org/wiki/Gillette_Stadium"
    - "https://en.wikipedia.org/wiki/Hard_Rock_Stadium"
    - "https://en.wikipedia.org/wiki/Highmark_Stadium_(New_York)"
    - "https://en.wikipedia.org/wiki/Huntington_Bank_Field"
    - "https://en.wikipedia.org/wiki/Lambeau_Field"
    - "https://en.wikipedia.org/wiki/Levi%27s_Stadium"
    - "https://en.wikipedia.org/wiki/Lincoln_Financial_Field"
    - "https://en.wikipedia.org/wiki/Lucas_Oil_Stadium"
    - "https://en.wikipedia.org/wiki/Lumen_Field"
    - "https://en.wikipedia.org/wiki/M%26T_Bank_Stadium"
    - "https://en.wikipedia.org/wiki/Mercedes-Benz_Stadium"
    - "https://en.wikipedia.org/wiki/MetLife_Stadium"
    - "https://en.wikipedia.org/wiki/Nissan_Stadium"
    - "https://en.wikipedia.org/wiki/Northwest_Stadium"
    - "https://en.wikipedia.org/wiki/NRG_Stadium"
    - "https://en.wikipedia.org/wiki/Paycor_Stadium"
    - "https://en.wikipedia.org/wiki/Raymond_James_Stadium"
    - "https://en.wikipedia.org/wiki/SoFi_Stadium"
    - "https://en.wikipedia.org/wiki/Soldier_Field"
    - "https://en.wikipedia.org/wiki/State_Farm_Stadium"
    - "https://en.wikipedia.org/wiki/U.S._Bank_Stadium"
ATTRIBUTES:
  TEAM_DETAILS:
    NAME: "//*[@id='main-content']/div/div/section/div/div/div/div[1]"
    TWITTER_LINK: "//a[contains(@href, 'twitter.com')]"
    TWITTER_TEXT: "span.nfl-o-social-link-bar__link-title"
    CONFERENCE: "//*[@id='main-content']/div/div/section/div/div/div/div[2]"
    VENUE: "//*[@id='main-content']/section[5]/div/div[1]/div/section/div/div[2]/ul/li[2]/div[2]"
    WEBSITE: "//*[@id='main-content']/div/section/div/div/div/ul/li[1]/a"
    HEAD_COACH: "//*[@id='main-content']/section[5]/div/div[1]/div/section/div/div[2]/ul/li[1]/div[2]"
  VENUES:
    NAME: "//table[contains(@class,'infobox')]//caption"
    SURFACE: "//th[@class='infobox-label'][contains(., 'Surface')]/following-sibling::td[1]"
    CAPACITY: "//th[@class='infobox-label'][contains(., 'Capacity')]/following-sibling::td[1]"
    LATLON_DECIMAL: "//span[contains(@class, 'geo-dec')]/text()"
    WEBSITE: "//tr[th[contains(., 'Website')]]/following-sibling::tr[1]/td//a/@href"
