LINKS:
  ESPN_TEAMS: "https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams?limit=200000"
  NCAA_TEAMS:
    - "https://www.ncaa.com/stats/football/fcs/current/team/27"
    - "https://www.ncaa.com/stats/football/fcs/current/team/27/p2"
    - "https://www.ncaa.com/stats/football/fcs/current/team/27/p3"
    - "https://www.ncaa.com/stats/football/fbs/current/team/27"
    - "https://www.ncaa.com/stats/football/fbs/current/team/27/p2"
    - "https://www.ncaa.com/stats/football/fbs/current/team/27/p3"
    - "https://www.ncaa.com/stats/football/d2/current/team/27"
    - "https://www.ncaa.com/stats/football/d2/current/team/27/p2"
    - "https://www.ncaa.com/stats/football/d2/current/team/27/p3"
    - "https://www.ncaa.com/stats/football/d2/current/team/27/p4"
    - "https://www.ncaa.com/stats/football/d3/current/team/27"
    - "https://www.ncaa.com/stats/football/d3/current/team/27/p2"
    - "https://www.ncaa.com/stats/football/d3/current/team/27/p3"
    - "https://www.ncaa.com/stats/football/d3/current/team/27/p4"
    - "https://www.ncaa.com/stats/football/d3/current/team/27/p5"
  NCAA_COACHES:
    - "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_I_FBS_football_coaches"
    - "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_II_football_coaches"
    - "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_III_football_coaches"
    - "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_I_FCS_football_coaches"
  NCAA_IDS:
    - "https://stats.ncaa.org/rankings/national_ranking?academic_year=2025.0&division=11.0&ranking_period=84.0&sport_code=MFB&stat_seq=22.0"
    - "https://stats.ncaa.org/rankings/national_ranking?academic_year=2025.0&division=12.0&ranking_period=39.0&sport_code=MFB&stat_seq=27.0"
    - "https://stats.ncaa.org/rankings/national_ranking?academic_year=2025.0&division=2.0&ranking_period=34.0&sport_code=MFB&stat_seq=27.0"
    - "https://stats.ncaa.org/rankings/national_ranking?academic_year=2025.0&division=3.0&ranking_period=30.0&sport_code=MFB&stat_seq=27.0"
  FBS_VENUES: "https://en.wikipedia.org/wiki/List_of_NCAA_Division_I_FBS_football_stadiums"
  FCS_VENUES: "https://en.wikipedia.org/wiki/List_of_NCAA_Division_I_FCS_football_stadiums"
ATTRIBUTES:
  NCAA_TEAM_REF: "td.reclass a.skipMask[href^='/teams/']"
  NCAA_TEAMS:
    ROWS: "tr"
    COLUMNS: "td"
    COLUMN_NUMBER: 2
    IMG_SRC: ".//img/@src"
    SCHOOL_URL: ".//a[@class='school']/@href"
    SCHOOL_NAME: ".//a[@class='school']"
  "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_I_FBS_football_coaches": 
    TABLE: "(//table)[1]"
  "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_II_football_coaches": 
    TABLE: "(//table)[2]"
  "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_III_football_coaches": 
    TABLE: "(//table)[1]"
  "https://en.wikipedia.org/wiki/List_of_current_NCAA_Division_I_FCS_football_coaches": 
    TABLE: "(//table)[2]"
  NCAA_DETAILED:
    CONFERENCE: "//dt[text()='Conference']/following-sibling::dd[1]"
    NICKNAME: "//dt[text()='Nickname']/following-sibling::dd[1]"
    COLORS: "//dt[text()='Colors']/following-sibling::dd[1]"
    SCHOOL: "h1.school-name"
    WEBSITE: "span.icon-web + .info"
    TWITTER: "span.icon-twitter + .info"
  NCAA_STAT:
    HEAD_COACH: "//div[contains(@class,'card-header') and contains(text(), 'Coach')]/following-sibling::div//a"
    VENUE: "//div[contains(@class, 'card-header') and contains(text(), 'Stadium')]/following-sibling::div//dt[contains(text(), 'Name:')]/following-sibling::dd"
  VENUES:
    NAME: "//table[contains(@class,'infobox')]//caption"
    LOCATION: "//th[@class='infobox-label'][contains(., 'Location')]/following-sibling::td[1]"
    LATLON_DECIMAL: "//span[contains(@class, 'geo-dec')]/text()"
    SURFACE: "//th[@class='infobox-label'][contains(., 'Surface')]/following-sibling::td[1]"
