LINKS:
  ESPN_TEAMS: "https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams?limit=200000"
  OFFENSIVE_COORDINATORS: "https://en.wikipedia.org/wiki/List_of_current_NFL_offensive_coordinators"
  DEFENSIVE_COORDINATORS: "https://en.wikipedia.org/wiki/List_of_current_NFL_defensive_coordinators"
  TEAM_DETAILS:
    - "https://www.nfl.com/teams/arizona-cardinals/"
    - "https://www.nfl.com/teams/atlanta-falcons/"
    - "https://www.nfl.com/teams/baltimore-ravens/"
    - "https://www.nfl.com/teams/buffalo-bills/"
    - "https://www.nfl.com/teams/carolina-panthers/"
    - "https://www.nfl.com/teams/chicago-bears/"
    - "https://www.nfl.com/teams/cincinnati-bengals/"
    - "https://www.nfl.com/teams/cleveland-browns/"
    - "https://www.nfl.com/teams/dallas-cowboys/"
    - "https://www.nfl.com/teams/denver-broncos/"
    - "https://www.nfl.com/teams/detroit-lions/"
    - "https://www.nfl.com/teams/green-bay-packers/"
    - "https://www.nfl.com/teams/houston-texans/"
    - "https://www.nfl.com/teams/indianapolis-colts/"
    - "https://www.nfl.com/teams/jacksonville-jaguars/"
    - "https://www.nfl.com/teams/kansas-city-chiefs/"
    - "https://www.nfl.com/teams/las-vegas-raiders/"
    - "https://www.nfl.com/teams/los-angeles-chargers/"
    - "https://www.nfl.com/teams/los-angeles-rams/"
    - "https://www.nfl.com/teams/miami-dolphins/"
    - "https://www.nfl.com/teams/minnesota-vikings/"
    - "https://www.nfl.com/teams/new-england-patriots/"
    - "https://www.nfl.com/teams/new-orleans-saints/"
    - "https://www.nfl.com/teams/new-york-giants/"
    - "https://www.nfl.com/teams/new-york-jets/"
    - "https://www.nfl.com/teams/philadelphia-eagles/"
    - "https://www.nfl.com/teams/pittsburgh-steelers/"
    - "https://www.nfl.com/teams/san-francisco-49ers/"
    - "https://www.nfl.com/teams/seattle-seahawks/"
    - "https://www.nfl.com/teams/tampa-bay-buccaneers/"
    - "https://www.nfl.com/teams/tennessee-titans/"
    - "https://www.nfl.com/teams/washington-commanders/"
ATTRIBUTES:
  TEAM_DETAILS:
    NAME: "//*[@id='main-content']/div/div/section/div/div/div/div[1]"
    TWITTER_LINK: "//a[contains(@href, 'twitter.com')]"
    TWITTER_TEXT: "span.nfl-o-social-link-bar__link-title"
    CONFERENCE: "//*[@id='main-content']/div/div/section/div/div/div/div[2]"
    VENUE: "//*[@id='main-content']/section[5]/div/div[1]/div/section/div/div[2]/ul/li[2]/div[2]"
    WEBSITE: "//*[@id='main-content']/div/section/div/div/div/ul/li[1]/a"
    HEAD_COACH: "//*[@id='main-content']/section[5]/div/div[1]/div/section/div/div[2]/ul/li[1]/div[2]"
