name: Update Venues Release

on:
  push:
    paths:
      - 'R/players/*.R'
  workflow_dispatch:

jobs:
  update-release:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/cullenchampagne1/sportsr:master

    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout repository (full history & tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mark Working Directory as Safe
        run: |
          git config --global --add safe.directory "$PWD"

      - name: Ensure data/raw exists
        run: mkdir -p data/raw
    
      - name: Restore cached raw data
        uses: actions/cache@v3
        with:
          path: data/raw
          key: data-raw-cache
          restore-keys: |
            data-raw-cache

      - name: Run update Players release script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x .github/scripts/update_players_release.sh
          .github/scripts/update_venues_players.sh data/processed
      
